// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  graphqlEndpoint:
    "https://sezfj6g5svchbnsdotgc6jnnga.appsync-api.us-east-1.amazonaws.com/graphql",
  region: "us-east-1",
  authenticationType: "API_KEY",
  apiKey: "da2-njpqbztig5ebzmoqwj2ifqawli"
};

export default awsmobile;
